# Generated by Django 4.0.2 on 2022-08-29 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcatgeory',
            new_name='subcategory',
        ),
    ]
